# Generated by Django 6.0 on 2025-12-25 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collision_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('occurred_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quadrant', models.CharField(choices=[('NW', 'NW'), ('NE', 'NE'), ('SW', 'SW'), ('SE', 'SE'), ('UNK', 'Unknown')], db_index=True, default='UNK', max_length=3)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('count', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('location_text', models.CharField(blank=True, max_length=255)),
                ('intersection_key', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CityDailyWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('weather_day_city', models.CharField(blank=True, choices=[('DRY', 'Dry'), ('WET', 'Wet'), ('SNY', 'Snowy')], max_length=3, null=True)),
                ('freeze_day_city', models.BooleanField(blank=True, null=True)),
                ('t_max_avg', models.FloatField(blank=True, null=True)),
                ('t_min_avg', models.FloatField(blank=True, null=True)),
                ('precip_any', models.BooleanField(blank=True, null=True)),
                ('snow_any', models.BooleanField(blank=True, null=True)),
                ('agreement_ratio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='core_cityda_date_bc6fdc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='core.collision')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['climate_id'], name='core_weathe_climate_31ee06_idx')],
            },
        ),
        migrations.AddField(
            model_name='collision',
            name='nearest_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nearest_collisions', to='core.weatherstation'),
        ),
        migrations.CreateModel(
            name='WeatherObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('t_max_c', models.FloatField(blank=True, null=True)),
                ('t_min_c', models.FloatField(blank=True, null=True)),
                ('t_mean_c', models.FloatField(blank=True, null=True)),
                ('total_rain_mm', models.FloatField(blank=True, null=True)),
                ('total_snow_cm', models.FloatField(blank=True, null=True)),
                ('total_precip_mm', models.FloatField(blank=True, null=True)),
                ('snow_on_ground_cm', models.FloatField(blank=True, null=True)),
                ('gust_dir_10deg', models.IntegerField(blank=True, null=True)),
                ('gust_kmh', models.IntegerField(blank=True, null=True)),
                ('weather_day', models.CharField(blank=True, choices=[('DRY', 'Dry'), ('WET', 'Wet'), ('SNY', 'Snowy')], max_length=3, null=True)),
                ('freeze_day', models.BooleanField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.weatherstation')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='core_weathe_date_c7cd90_idx'), models.Index(fields=['station', 'date'], name='core_weathe_station_c84bed_idx'), models.Index(fields=['weather_day'], name='core_weathe_weather_488b25_idx'), models.Index(fields=['freeze_day'], name='core_weathe_freeze__3acf3d_idx')],
                'unique_together': {('station', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='collision',
            index=models.Index(fields=['date', 'quadrant'], name='core_collis_date_b631a0_idx'),
        ),
        migrations.AddIndex(
            model_name='collision',
            index=models.Index(fields=['occurred_at'], name='core_collis_occurre_8c182c_idx'),
        ),
        migrations.AddIndex(
            model_name='collision',
            index=models.Index(fields=['nearest_station'], name='core_collis_nearest_bda3f5_idx'),
        ),
    ]
