# Generated by Django 6.0 on 2025-12-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='citydailyweather',
            index=models.Index(fields=['weather_day_city'], name='core_cityda_weather_fb4a7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='collision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('hour__gte', 0), ('hour__lte', 23)), ('hour__isnull', True), _connector='OR'), name='collision_hour_range'),
        ),
        migrations.AddConstraint(
            model_name='collision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('weekday__gte', 0), ('weekday__lte', 6)), ('weekday__isnull', True), _connector='OR'), name='collision_weekday_range'),
        ),
        migrations.AddConstraint(
            model_name='collision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('month__gte', 1), ('month__lte', 12)), ('month__isnull', True), _connector='OR'), name='collision_month_range'),
        ),
    ]
